domain: example.com
url: https://example.com

title: Mirko
email: wind@example.com
author: Wind Sample

lang: en

plugins:
  - jekyll-seo-tag

color: "#13ccf9" 

# disqus:
#   shortname: example-com
#
# rrss:
  discord: http://localhost:5173/
  facebook: http://localhost:5173/
  # twitter: Hola
  # instagram: Hola
  # linkedin: Hola
  # pinterest: hola
  # whatsapp: 123
  # telegram: 123
  # email: email
